#!/bin/bash 

function parse_git_branch () {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# PS1 Colors?
RED="\e[0;31m"
YELLOW="\e[0;33m"
GREEN="\e[0;32m"
PURPLE="\e[0;35m"
BLUE="\e[0;34m"
NO_COLOR="\e[0m"

# Echo colors?
ECHO_NO_COLOR="\033[0m"
ECHO_BOLD_RED="\033[1;31m"
ECHO_BOLD_CYAN="\033[1;36m"
ECHO_BOLD_PURPLE="\033[1;35m"
ECHO_BOLD_PURPLE="\033[1;35m"

function get_git_color() {
  if [[ $(parse_git_branch) =~ "master" ]]
  then
    echo -e "$ECHO_BOLD_CYAN$(parse_git_branch)$ECHO_NO_COLOR"
  elif [[ $(parse_git_branch) =~ "prod" ]]
  then
    echo -e "$ECHO_BOLD_RED$(parse_git_branch)$ECHO_NO_COLOR"
  else
    echo -e "$ECHO_BOLD_PURPLE$(parse_git_branch)$ECHO_NO_COLOR"
  fi
}

export PS1="$RED\u$NO_COLOR$GREEN@$NO_COLOR${BLUE}${_HOSTNAME}$NO_COLOR$YELLOW:\w$NO_COLOR\$(get_git_color)$PURPLE\$$NO_COLOR \n∴ "
